config/routes.rb
Rails.application.routes.draw do

  get '/' => 'posts#index'

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end

  resources :users
  resources :comments

  resources :posts do
      resources :comments
  end
resources :users do

end

end

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <link rel="icon" href="../../favicon.ico">

  <title>Fixed Top Navbar Example for Bootstrap</title>


  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">My First Blog</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class><a href="/">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%if (session[:user_id])%><%=logout_url%><%else%><%=login_url%><%end%>"><%if (session[:user_id])%>logout<%else%>login<%end%></a></li>
        <li><a href="<%if (session[:user_id])%><%=user_path(session[:user_id])%><%else%><%=new_user_url%><%end%>"><%if (session[:user_id])%><%=User.find_by_id(session[:user_id]).email%><%else%>Signup<%end%></a></li>
        <li><a href="<%=new_post_url%>">New Post</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <%=render('layouts/navbar')%>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="position: absolute;top: 10%;" >
<div class="container">
<%= yield %>
</div>
</body>
</html>